USE [DS_HSDW_App]
GO

IF EXISTS (SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA='Rptg'
    AND TABLE_TYPE='BASE TABLE' 
    AND TABLE_NAME='CHCAHPS_TB_R_All_PG_Database_CMS_View')
   DROP TABLE Rptg.CHCAHPS_TB_R_All_PG_Database_CMS_View
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Rptg].[CHCAHPS_TB_R_All_PG_Database_CMS_View](
	[VALUE] [NUMERIC](4, 1) NULL,
	[DOMAIN_QUESTION] [VARCHAR](100) NULL,
	[PERCENTILE_RANK] [INT] NULL,
	[RPT_PRD_BGN] [DATE] NULL,
	[RPT_PRD_END] [DATE] NULL,
	[sk_Dim_PG_Question] [INTEGER] NULL,
	[QUESTION_TEXT] [VARCHAR](300) NULL,
	[DOMAIN] [VARCHAR](100) NULL,
	[Load_Dtm] [SMALLDATETIME] NULL
) ON [PRIMARY]
GO


