USE [DS_HSDW_App_Dev]
GO

IF EXISTS (SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA='Rptg'
    AND TABLE_TYPE='BASE TABLE' 
    AND TABLE_NAME='CHCAHPS_PX_Goal_Setting')
   DROP TABLE Rptg.CHCAHPS_PX_Goal_Setting
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Rptg].[CHCAHPS_PX_Goal_Setting](
	[SERVICE_LINE] [VARCHAR](150) NULL,
	[UNIT_LOCATION] [VARCHAR](150) NULL,
	[DOMAIN_QUESTION] [VARCHAR](150) NULL,
	[GOAL] [DECIMAL] (4,3) NULL,
	[PERCENTILE] [INT] NULL,
	[PERCENTILE_SL] [INT] NULL,
	[Load_Dtm] [SMALLDATETIME] NULL
) ON [PRIMARY]
GO


