USE [DS_HSDW_App]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA='Rptg'
    AND TABLE_TYPE='BASE TABLE' 
    AND TABLE_NAME='CHCAHPS_Locations')
   DROP TABLE Rptg.CHCAHPS_Locations
GO

CREATE TABLE [Rptg].[CHCAHPS_Locations](
	[SERVICE_LINE] [VARCHAR](500) NULL,
	[CLINIC] [VARCHAR](500) NULL,
	[EPIC_DEPARTMENT_ID] [VARCHAR](500) NULL,
	[Load_Dtm] [SMALLDATETIME] NULL
) ON [PRIMARY]
GO

ALTER TABLE [Rptg].[CHCAHPS_Locations] ADD  DEFAULT (GETDATE()) FOR [Load_Dtm]
GO


