USE [DS_HSDW_App]
GO

IF EXISTS (SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA='Rptg'
    AND TABLE_TYPE='BASE TABLE' 
    AND TABLE_NAME='CHCAHPS_Goals')
   DROP TABLE Rptg.CHCAHPS_Goals
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Rptg].[CHCAHPS_Goals](
	[SVC_CDE] [VARCHAR](2) NULL,
	[GOAL_YR] [INT] NULL,
	[SERVICE_LINE] [VARCHAR](150) NULL,
	[UNIT] [VARCHAR](150) NULL,
	[DOMAIN] [VARCHAR](150) NULL,
	[GOAL] [DECIMAL](4, 3) NULL
) ON [PRIMARY]
GO


